- name: create s3 bucket
  hosts: all
  strategy: free
  gather_facts: False
  become: true
  become_user: root

  tasks:
       - name: Create a bucket
         s3:
           bucket: nknk
           mode: create
