- name: test playbook
  hosts: all
  strategy: free
  gather_facts: False
  become: true
  become_user: root

  tasks:

     - name: Install the httpd rpm
       yum: name=httpd state=removed
     - name: start the httpd service
       service: name=httpd state=started
